---
- name: Change grub-file /etc/default/grub
  hosts: node2.example.com
  tasks:
  - name: Add parametrs net.ifnames=0 and biosdevname=0
    lineinfile:
      path: /etc/default/grub
      state: present
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*net\.ifnames=\d biosdevname=\d)\"[^\"]+)(\".*)'
      backrefs: yes
      line: '\1 net.ifnames=0 biosdevname=0\2'
  - name: Make GRUB config
    command: 'grub2-mkconfig -o /boot/grub2/grub.cfg'
...
